global:
    int: 8888
    float: 3.14
    string: brand new name
    int_vec: [4, 5, 6]
    int_list: [4, 5, 6]
    int_set: [4, 5, 6]
    int_unordered_set: [4, 5, 6]
    map_string2int:
        key1: 3
        key2: 4
    unordered_map_string2int:
        key1: 3
        key2: 4
class:
    person:
        name: name1
        age: 10
        sex: true
    map:
        name2:
            name: name2
            age: 20
            sex: true
        name3:
            name: name3
            age: 30
            sex: false
    vec_map:
        name4:
            - name: name4
              age: 40
              sex: true
        name5:
            - name: name5
              age: 50
              sex: false
            